[project]
name = "financial-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling-parse>=7.19.1",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-docling>=3.0.0",
    "langchain-google-genai>=4.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-postgres>=0.0.18",
    "pypdf>=6.18.1",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
financial-rag = "financial_rag.main:main"


[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
